In [1]:
import json
dreamprm_meta = "DreamPRM/data/meta.json"
dreamprm_train = "DreamPRM/data/train.json"
MATH_path = "MATH"

import os
MATH = {'train':{}, 'test':{}}
for i in MATH:
    path = os.path.join(MATH_path, i)
    for j in os.listdir(path):
        MATH[i][j] = [os.path.join(path, j, k) for k in os.listdir(os.path.join(path, j)) if k.endswith('.json')]
        

prm800k_path = "prm800k/prm800k/data"
prm_split_path = {"test": "prm800k/prm800k/math_splits/test.jsonl", 
                 "train": "prm800k/prm800k/math_splits/train.jsonl"}
prm800k  = {}

for phase in range(1,3):
    prm800k[f"phase{phase}"] = {}
    for type in ['train', 'test']:
        prm800k[f"phase{phase}"][type] = f"{prm800k_path}/phase{phase}_{type}.jsonl"
        


In [1]:
import torch

a = torch.tensor([[[-0.0854, -1.0391],
         [-0.4590, -0.3770],
         [ 1.7734,  1.7188],
         [ 3.2656,  2.0625],
         [-0.3594, -0.4004],
         [ 1.5156, -0.7891],
         [ 1.3281, -0.1338],
         [ 1.9922,  0.2129],
         [ 2.6094,  0.0396],
         [ 2.5469, -2.6250],
         [ 0.3594,  0.6953],
         [ 2.3906, -0.5273],
         [ 1.9531,  1.7188],
         [ 0.4473,  0.2441],
         [-0.0688,  0.1157],
         [-2.3750,  2.8125],
         [ 0.5078,  1.4062],
         [ 0.7539,  1.5312],
         [ 0.2871,  0.8516],
         [ 0.6250, -0.4766],
         [-1.3750,  1.1797],
         [-0.3223,  0.0217],
         [ 3.2031, -0.4434],
         [ 3.5000,  2.0781],
         [ 3.3750,  1.7422],
         [ 4.0000,  2.4219],
         [ 2.6406,  2.6875],
         [ 1.4922, -0.2734],
         [ 1.4844,  2.3281],
         [ 2.1719,  0.5156],
         [ 1.9062,  0.2207],
         [ 2.3438,  1.5234],
         [ 1.5469,  0.8750],
         [ 0.2539,  2.2344],
         [ 1.7344,  0.2578],
         [ 1.2500,  0.3906],
         [ 1.0859,  0.5234],
         [ 3.2500,  0.8398],
         [ 1.8828,  0.4648],
         [ 3.6719, -0.0854],
         [ 3.0938, -2.0312],
         [ 2.2031, -0.9414],
         [ 1.9375, -0.2363],
         [ 2.0625,  1.5078],
         [ 0.0087,  0.3555],
         [ 1.8438,  1.2578],
         [ 2.0781,  0.1475],
         [ 0.2949, -0.0503],
         [-2.7031, -0.0566],
         [-0.6797,  1.0469],
         [ 0.5742, -0.6211],
         [ 1.2422, -0.2949],
         [ 3.5781, -0.3223],
         [-0.2559, -0.1348],
         [ 3.2969, -0.2988],
         [ 0.0559,  0.4883],
         [ 2.3906,  1.9609],
         [ 4.6875,  1.8672],
         [ 3.1875,  1.6797],
         [ 2.5625,  1.9922],
         [ 2.2812,  0.1436],
         [-0.2676,  0.2578],
         [ 1.9688,  0.9414],
         [ 1.8594,  0.0791],
         [ 1.7734,  0.1787],
         [ 2.2031,  0.0625],
         [ 1.9141, -0.4512],
         [ 2.2500,  0.0273],
         [-0.6016, -0.7656],
         [ 1.2422,  0.5586],
         [ 1.9531, -0.3105],
         [ 0.4004, -0.8320],
         [-0.8281, -0.9961],
         [ 1.6719,  0.8594],
         [ 1.6797, -0.2793],
         [-0.6875, -0.9531],
         [ 3.4531,  0.0850],
         [ 5.1875,  0.2578],
         [ 1.5078, -1.0312],
         [ 0.2559,  0.3906],
         [ 1.0312, -1.1094],
         [ 2.3906,  0.7891],
         [ 4.1562,  0.4062],
         [ 3.0781,  0.1226],
         [ 1.9922, -0.0483],
         [ 2.7812,  1.2188],
         [ 2.3438,  3.9062],
         [ 1.4297, -0.6016],
         [ 0.8203, -0.2676],
         [ 2.1406,  0.9219],
         [ 1.1250,  0.5703],
         [ 0.0815,  0.4648],
         [ 2.7500,  0.8555],
         [ 0.6680, -0.8438],
         [ 0.1299,  0.6016],
         [ 3.7188,  0.6914],
         [ 4.5938, -0.8945],
         [ 3.4375, -0.7188],
         [ 0.8125, -1.4688],
         [ 2.5156, -0.9844],
         [ 1.9062,  1.6016],
         [ 1.3828,  1.2969],
         [ 0.3457,  1.0625],
         [-0.8867, -1.2344],
         [ 2.7031,  1.1719],
         [ 1.5000, -0.7930],
         [ 1.8438,  2.0781],
         [ 0.8984, -0.5273],
         [ 0.9219,  1.5859],
         [ 1.6562, -0.2871],
         [ 2.6875,  1.0391],
         [ 0.6406,  1.4062],
         [ 1.5547,  3.2031],
         [ 3.5469,  3.3438],
         [ 2.5469,  1.3203],
         [ 2.0938,  0.7422],
         [ 3.3125,  0.1719],
         [ 0.1611, -0.3223],
         [ 1.4922,  1.7266],
         [ 3.5625,  0.9844],
         [ 1.0547, -0.1309],
         [ 1.1562,  1.7422],
         [ 0.8320,  2.2500],
         [ 0.8047, -0.4043],
         [ 0.5586, -0.8203],
         [ 0.8008,  0.6523],
         [ 1.3672, -0.1406],
         [ 0.8438, -0.2773],
         [ 1.3984,  0.5898],
         [ 0.4355, -2.8281],
         [-0.2949,  0.6094],
         [ 1.8203,  0.1387],
         [-0.1650, -1.0234],
         [ 2.2656,  0.5703],
         [ 0.6602,  1.2656],
         [ 0.5312,  0.2041],
         [ 1.0938, -0.4062],
         [ 0.0168,  0.1191],
         [ 1.1250,  0.9961],
         [ 1.2734,  0.7812],
         [-1.2656,  0.8984],
         [-0.3047,  1.3984],
         [-0.8125,  1.5156],
         [ 2.0781,  1.2891],
         [ 1.3594,  1.8281],
         [ 1.4531,  2.2969],
         [ 2.0156,  2.2656],
         [ 1.2969,  0.3633],
         [ 0.7617,  0.9961],
         [ 1.3125,  0.8672],
         [ 0.8242,  1.0781],
         [ 2.1562,  1.4766],
         [ 1.6406, -0.5508],
         [ 2.2500,  0.2158],
         [ 0.8828,  1.0312],
         [ 2.9531,  1.3906],
         [-0.0649,  1.8516],
         [ 2.8750,  1.1172],
         [ 2.7188, -0.4238],
         [ 1.5625,  1.5469],
         [ 3.1406,  1.3359]]])



In [3]:
a.shape


torch.Size([1, 161, 2])

In [12]:
import torch.nn.functional as F
F.softmax(a).shape

/tmp/ipykernel_58365/3584890108.py:2: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(a).shape


torch.Size([1, 161, 2])

In [2]:
import pandas as pd
ph2 = pd.read_json(path_or_buf=prm800k['phase2']['train'], lines=True)
ph1 = pd.read_json(path_or_buf=prm800k['phase1']['train'], lines=True)

train_ph = pd.concat([ph1, ph2], ignore_index=True)

In [3]:
## convert question column to str
train_ph['question_str'] = train_ph['question'].astype(str)

## get question key alone from dict:
train_ph['problem_nly'] = train_ph['question'].apply(lambda x: x['problem'])


train_ph['label_str'] = train_ph['label'].astype(str)

In [4]:
len(train_ph['problem_nly'].unique())

10835

In [5]:
### calculate unique questions:
unique_questions = train_ph['question_str'].unique()
print(f"Total unique questions in phase 1 and 2 combined: {len(unique_questions)} out of {len(train_ph)} total questions.")

Total unique questions in phase 1 and 2 combined: 74845 out of 98731 total questions.


In [6]:
### calculate unique questions:
unique_questions = train_ph['label_str'].unique()
print(f"Total unique solutions in phase 1 and 2 combined: {len(unique_questions)} out of {len(train_ph)} total questions.")

Total unique solutions in phase 1 and 2 combined: 98728 out of 98731 total questions.


In [7]:
### take an example where question_str is not unique
### groupby question_str and count occurrences
duplicates = train_ph.groupby('question_str').size().reset_index(name='count')
duplicates = duplicates[duplicates['count'] > 10]
duplicates_sample_question_str = duplicates.iloc[0]['question_str']
duplicates


question_str  count
283    {'problem': "A right circular cone has base ra...    112
1001   {'problem': "How many 10-digit positive intege...    124
1296   {'problem': "In order to compute the area of a...    452
1764   {'problem': "Megan has lost Fatima's phone num...    452
2170   {'problem': "The Bank of Springfield's Super H...    441
...                                                  ...    ...
72408  {'problem': 'What is the sum of all positive i...    116
72537  {'problem': 'What is the sum of all the three-...     47
73169  {'problem': 'What is the value of $\\displayst...    431
74053  {'problem': 'When each edge of a cube is incre...    433
74779  {'problem': 'You have a rectangular prism box ...    107

[109 rows x 2 columns]

In [8]:
duplicate = train_ph[train_ph['question_str'] == duplicates_sample_question_str]
duplicate

labeler                  timestamp  \
80225  e90a38f3-3135-4465-87af-3e6322e3d772 2022-10-25 21:13:14.526438   
81912  e492b9ab-1083-4bb9-b67a-98531c908684 2022-10-24 21:29:52.958101   
82103  525a7498-b258-4b2b-a1b1-a37aed486603 2022-10-24 18:14:56.943519   
82157  0b3ebf0e-2af8-430f-94f8-00f7e1b4a947 2022-10-24 13:17:25.550388   
82164  ad59f612-1034-4fc0-9f39-84a57b4aa452 2022-10-24 13:01:21.810638   
...                                     ...                        ...   
88359  e214792c-cc80-402d-9699-7124b8a2d0fd 2022-10-18 12:33:39.091175   
88424  5a1ab09c-9262-405a-aa6f-b44212a6a84b 2022-10-18 07:11:20.382824   
88476  82c5600e-9411-448b-a98e-86c298d6900e 2022-10-19 00:05:43.672643   
88894  9c8a2077-c54b-4fb5-9225-5e0f3c4db30d 2022-10-19 01:34:18.163016   
90804  88155943-d0dc-4c73-8e21-0f35c0cf8f0a 2022-10-15 00:24:56.846210   

       generation  is_quality_control_question  is_initial_screening_question  \
80225         2.0                         True                          False   
81912         2.0                         True                          False   
82103         2.0                         True                          False   
82157         2.0                         True                          False   
82164         2.0                         True                          False   
...           ...                          ...                            ...   
88359         2.0                         True                          False   
88424         2.0                         True                          False   
88476         2.0                         True                          False   
88894         2.0                         True                          False   
90804         2.0                         True                          False   

                                                question  \
80225  {'problem': 'A right circular cone has base ra...   
81912  {'problem': 'A right circular cone has base ra...   
82103  {'problem': 'A right circular cone has base ra...   
82157  {'problem': 'A right circular cone has base ra...   
82164  {'problem': 'A right circular cone has base ra...   
...                                                  ...   
88359  {'problem': 'A right circular cone has base ra...   
88424  {'problem': 'A right circular cone has base ra...   
88476  {'problem': 'A right circular cone has base ra...   
88894  {'problem': 'A right circular cone has base ra...   
90804  {'problem': 'A right circular cone has base ra...   

                                                   label  \
80225  {'steps': [{'completions': [{'text': 'I will s...   
81912  {'steps': [{'completions': [{'text': 'I will s...   
82103  {'steps': [{'completions': [{'text': 'I will s...   
82157  {'steps': [{'completions': [{'text': 'I will s...   
82164  {'steps': [{'completions': [{'text': 'I will s...   
...                                                  ...   
88359  {'steps': [{'completions': [{'text': 'I will s...   
88424  {'steps': [{'completions': [{'text': 'I will s...   
88476  {'steps': [{'completions': [{'text': 'I will s...   
88894  {'steps': [{'completions': [{'text': 'I will s...   
90804  {'steps': [{'completions': [{'text': 'I will s...   

                                            question_str  \
80225  {'problem': "A right circular cone has base ra...   
81912  {'problem': "A right circular cone has base ra...   
82103  {'problem': "A right circular cone has base ra...   
82157  {'problem': "A right circular cone has base ra...   
82164  {'problem': "A right circular cone has base ra...   
...                                                  ...   
88359  {'problem': "A right circular cone has base ra...   
88424  {'problem': "A right circular cone has base ra...   
88476  {'problem': "A right circular cone has base ra...   
88894  {'problem': "A right circular cone has base ra...   
90804  {'problem': "A right circular cone has base ra...   

           

In [9]:
len(duplicate.label_str.unique())

112

In [10]:
len(duplicate.iloc[1]['label']['steps']), len(duplicate.iloc[2]['label']['steps'])

(17, 17)

In [ ]:

duplicate.iloc[1]['label']['total_time'], duplicate.iloc[2]['label']['total_time']

(4951811, 193218)

In [4]:
a = torch.randn(2)
torch.sigmoid(a[1] - a[0])

tensor(0.9672)

In [6]:
torch.nn.functional.softmax(a, dim=0)

tensor([0.0328, 0.9672])

In [ ]:
import torch
a = torch.randn(3,2)
torch.sigmoid(a)

tensor([[0.4701, 0.2347],
        [0.6011, 0.6441],
        [0.4579, 0.0389]])

In [12]:
c=0
for i,j in zip(duplicate.iloc[3]['label']['steps'], duplicate.iloc[5]['label']['steps']):
    print(f"Step {c}:")
    c+=1
    if i != j:
        print(i)
        print(j)

Step 0:
Step 1:
Step 2:
Step 3:
Step 4:
{'completions': [{'text': 'I will label this distance $x$.', 'rating': 0, 'flagged': None}], 'human_completion': None, 'chosen_completion': 0}
{'completions': [{'text': 'I will label this distance $x$.', 'rating': 1, 'flagged': None}], 'human_completion': None, 'chosen_completion': 0}
Step 5:
Step 6:
Step 7:
Step 8:
Step 9:
Step 10:
Step 11:
Step 12:
Step 13:
Step 14:
{'completions': [{'text': 'I have $h/r = h/(17x) = \\frac{h}{17\\frac{h}{\\sqrt {290}}} = \\frac{\\sqrt {290}}{17}$.', 'rating': 1, 'flagged': None}], 'human_completion': None, 'chosen_completion': 0}
{'completions': [{'text': 'I have $h/r = h/(17x) = \\frac{h}{17\\frac{h}{\\sqrt {290}}} = \\frac{\\sqrt {290}}{17}$.', 'rating': 0, 'flagged': None}], 'human_completion': None, 'chosen_completion': 0}
Step 15:
{'completions': [{'text': 'This is already in the form $m\\sqrt {n}$, where $m = 1$ and $n = 290$.', 'rating': -1, 'flagged': None}, {'text': 'This is already in the form $m\\sqr

In [13]:

{'input_ids': [23085, 1372, 374, 8131, 11, 220, 24, 13, 23, 476, 220, 24, 13, 16, 16, 30, 16, 16, 374, 7046, 1091, 220, 23, 13, 198, 39, 763, 11, 220, 24, 13, 16, 16, 861, 220, 24, 13, 23, 13, 198],
         'labels': [-100, -100, -100, -100, -100, -100, -100, -100, 1, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 0]}
       

{'input_ids': [23085,
  1372,
  374,
  8131,
  11,
  220,
  24,
  13,
  23,
  476,
  220,
  24,
  13,
  16,
  16,
  30,
  16,
  16,
  374,
  7046,
  1091,
  220,
  23,
  13,
  198,
  39,
  763,
  11,
  220,
  24,
  13,
  16,
  16,
  861,
  220,
  24,
  13,
  23,
  13,
  198],
 'labels': [-100,
  -100,
  -100,
  -100,
  -100,
  -100,
  -100,
  -100,
  1,
  -100,
  -100,
  -100,
  -100,
  -100,
  -100,
  -100,
  -100,
  -100,
  -100,
  -100,
  -100,
  -100,
  -100,
  0]}

In [14]:
print(f"Sample question_str with duplicates: {duplicates_sample_question_str}")
soltns = []
for labeled_solution in duplicate['label'].values:
    print("=====================================")


    soltn = [
    step["human_completion"] if step["chosen_completion"] is None
    else step["completions"][step["chosen_completion"]]["text"]
    for step in labeled_solution["steps"]
]
    print(len(soltn), soltn)
    
    soltns.append(str(soltn))
    
print(len(set(soltns)), len(soltns))


Sample question_str with duplicates: {'problem': "A right circular cone has base radius $r$ and height $h$. The cone lies on its side on a flat table. As the cone rolls on the surface of the table without slipping, the point where the cone's base meets the table traces a circular arc centered at the point where the vertex touches the table. The cone first returns to its original position on the table after making $17$ complete rotations. The value of $h/r$ can be written in the form $m\\sqrt {n}$, where $m$ and $n$ are positive integers and $n$ is not divisible by the square of any prime. Find $m + n$.", 'ground_truth_solution': 'The path is a circle with radius equal to the slant height of the cone, which is $\\sqrt {r^{2} + h^{2}}$. Thus, the length of the path is $2\\pi\\sqrt {r^{2} + h^{2}}$.\nAlso, the length of the path is 17 times the circumference of the base, which is $34r\\pi$. Setting these equal gives $\\sqrt {r^{2} + h^{2}} = 17r$, or $h^{2} = 288r^{2}$. Thus, $\\dfrac{h^{

In [15]:
import pandas as pd    

df = pd.read_json(path_or_buf=prm800k['phase1']['train'], lines=True)
df
# display(pd.read_json(path_or_buf=prm800k['phase2']['train'], lines=True))

labeler                  timestamp  \
0    e90a38f3-3135-4465-87af-3e6322e3d772 2022-07-13 18:55:54.496450   
1    e90a38f3-3135-4465-87af-3e6322e3d772 2022-07-17 16:56:51.323252   
2    e90a38f3-3135-4465-87af-3e6322e3d772 2022-07-02 18:33:27.255302   
3    d8aa7923-b970-45e1-9734-e4a7f6c4a7db 2022-07-17 16:56:53.345085   
4    debabc6d-f79c-4ee5-a9db-5e284390254c 2022-07-17 16:59:27.072495   
..                                    ...                        ...   
944  e90a38f3-3135-4465-87af-3e6322e3d772 2022-08-05 21:43:43.721301   
945  e90a38f3-3135-4465-87af-3e6322e3d772 2022-08-05 21:48:52.259330   
946  e90a38f3-3135-4465-87af-3e6322e3d772 2022-08-05 22:06:16.125858   
947  e90a38f3-3135-4465-87af-3e6322e3d772 2022-08-05 22:08:09.632793   
948  e90a38f3-3135-4465-87af-3e6322e3d772 2022-08-05 23:01:08.412712   

     generation  is_quality_control_question  is_initial_screening_question  \
0           NaN                        False                          False   
1           NaN                        False                          False   
2           NaN                        False                          False   
3           NaN                        False                          False   
4           NaN                        False                          False   
..          ...                          ...                            ...   
944         NaN                        False                          False   
945         NaN                        False                          False   
946         NaN                        False                          False   
947         NaN                        False                          False   
948         NaN                        False                          False   

                                              question  \
0    {'problem': 'How many seconds are in 7.8 minut...   
1    {'problem': 'How many positive two-digit integ...   
2    {'problem': 'The fifth and eighth terms of a g...   
3    {'problem': 'Find the value of $x$ that satisf...   
4    {'problem': 'What is the least three-digit who...   
..                                                 ...   
944  {'problem': 'Triangle $ABC$ is inscribed in ci...   
945  {'problem': 'Andrew and John are both Beatles ...   
946  {'problem': 'If the consecutive integers from ...   
947  {'problem': 'What is the remainder when $1 + 2...   
948  {'problem': 'One and one-half of what number i...   

                                                 label  
0    {'steps': [{'completions': [{'text': '7.8 minu...  
1    {'steps': [{'completions': [{'text': "Let's ca...  
2    {'steps': [{'completions': [{'text': 'So we ha...  
3    {'steps': [{'completions': [{'text': "Let's fi...  
4    {'steps': [{'completions': [{'text': 'So we wa...  
..                                                 ...  
944  {'steps': [{'completions': [{'text': "First, l...  
945  {'steps': [{'completions': [{'text': "So there...  
946  {'steps': [{'completions': [{'text': "Let's th...  
947  {'steps': [{'completions': [{'text': "Let's fi...  
948  {'steps': [{'completions': [{'text': 'We need ...  

[949 rows x 7 columns]

In [16]:
print(df.iloc[10]['question'].keys())
df.iloc[10]['question']['problem']

dict_keys(['problem', 'ground_truth_answer'])


'The numbers 60, 221, and 229 are the legs and hypotenuse of a right triangle.  Find the multiplicative inverse to 450 modulo 3599.  (Express your answer as an integer $n$ with $0\\leq n<3599$.)'

In [17]:
df.iloc[10]['label']

{'steps': [{'completions': [{'text': 'We can start by applying the Pythagorean theorem to the numbers 60, 221, and 229.',
     'rating': 1,
     'flagged': False}],
   'human_completion': None,
   'chosen_completion': 0},
  {'completions': [{'text': 'That will tell us if they do indeed form a right triangle.',
     'rating': -1,
     'flagged': False},
    {'text': 'That gives us $60^2 + 221^2 = 229^2$.',
     'rating': 1,
     'flagged': False},
    {'text': 'The Pythagorean theorem tells us that $60^2 + 221^2 = 229^2$.',
     'rating': 1,
     'flagged': False},
    {'text': 'That gives $60^2 + 221^2 = 229^2$.',
     'rating': 1,
     'flagged': False},
    {'text': 'That gives us $60^2 + 221^2 = 229^2$.',
     'rating': 1,
     'flagged': False},
    {'text': 'So $60^2 + 221^2 = 229^2$.', 'rating': 1, 'flagged': False},
    {'text': 'So $60^2 + 221^2 = 229^2$.', 'rating': 1, 'flagged': False}],
   'human_completion': None,
   'chosen_completion': 3},
  {'completions': [{'text': 'So 

In [18]:
for i in df.iloc[10]['label']['steps']:
    print(i['completions'])

[{'text': 'We can start by applying the Pythagorean theorem to the numbers 60, 221, and 229.', 'rating': 1, 'flagged': False}]
[{'text': 'That will tell us if they do indeed form a right triangle.', 'rating': -1, 'flagged': False}, {'text': 'That gives us $60^2 + 221^2 = 229^2$.', 'rating': 1, 'flagged': False}, {'text': 'The Pythagorean theorem tells us that $60^2 + 221^2 = 229^2$.', 'rating': 1, 'flagged': False}, {'text': 'That gives $60^2 + 221^2 = 229^2$.', 'rating': 1, 'flagged': False}, {'text': 'That gives us $60^2 + 221^2 = 229^2$.', 'rating': 1, 'flagged': False}, {'text': 'So $60^2 + 221^2 = 229^2$.', 'rating': 1, 'flagged': False}, {'text': 'So $60^2 + 221^2 = 229^2$.', 'rating': 1, 'flagged': False}]
[{'text': 'So $3600 + 48841 = 52629$, which is true.', 'rating': -1, 'flagged': False}, {'text': 'And if we simplify that a bit we see that it is true.', 'rating': -1, 'flagged': False}, {'text': 'Simplifying, we get $3600 + 48961 = 52801$.', 'rating': -1, 'flagged': False}, {

In [19]:
labeled_solution = df.iloc[10]

[
    step["human_completion"] if step["chosen_completion"] is None
    else step["completions"][step["chosen_completion"]]["text"]
    for step in labeled_solution["label"]["steps"]
]

['We can start by applying the Pythagorean theorem to the numbers 60, 221, and 229.',
 'That gives $60^2 + 221^2 = 229^2$.',
 {'text': 'Observe that $450=221+229$.',
  'rating': None,
  'source': 'human',
  'flagged': False},
 {'text': 'Rewrite the equation as $60^2=229^2-221^2=(221+229)(229-221)$.',
  'rating': None,
  'source': 'human',
  'flagged': False},
 'I see that $(221+229)$ is a factor on the right side.',
 {'text': 'Take this equation modulo $3599$.',
  'rating': None,
  'source': 'human',
  'flagged': False},
 'This means we can replace $221+229$ with $450$.',
 'And we can replace $229-221$ with $8$.',
 'So $60^2 \\equiv 450 \\cdot 8 \\pmod{3599}$.',
 {'text': 'We can calculate $60^2 \\pmod{3599}$.',
  'rating': None,
  'source': 'human',
  'flagged': False},
 'I find that $60^2 \\equiv 3600 \\equiv 1 \\pmod{3599}$.',
 'Now we can divide both sides by $8$.',
 {'text': 'So $450 \\cdot 8 \\equiv1\\pmod{3599}$.',
  'rating': None,
  'source': 'human',
  'flagged': False},
 'A 

In [20]:
train_split = pd.read_json(path_or_buf=prm_split_path["train"], lines=True)


In [21]:
train_split

problem  \
0      How many vertical asymptotes does the graph of...   
1       If $5x - 3 = 12$, what is the value of $5x + 3$?   
2      Ryan has 3 red lava lamps and 3 blue lava lamp...   
3      Alice wants to buy $3$ pounds of veal at the g...   
4      On the $xy$-plane, the origin is labeled with ...   
...                                                  ...   
11995  The product of two positive integers plus thei...   
11996  The volume of the box is 240 cubic units where...   
11997  Let \[f(n) =\n\begin{cases}\nn^2-1 & \text{ if...   
11998  Find the nonconstant polynomial $P(x)$ such th...   
11999  If $\sqrt2 \sin 10^\circ$ can be written as $\...   

                                                solution         answer  \
0      The denominator of the rational function facto...              2   
1      Adding 6 to both sides of $5x - 3 =12$ gives $...             18   
2      There are $\binom{6}{3}=20$ ways for Ryan to a...  \dfrac{7}{20}   
3      Since Alice wants to buy $3$ pounds of veal, w...           1.36   
4      From the M, we can proceed to four different A...             28   
...                                                  ...            ...   
11995  Let our numbers be $a$ and $b$ with $a>b.$ The...             19   
11996  The prime factorization of 240 is $2^4\cdot3\c...             10   
11997  Working from the inside out, since $2<4$ we ha...             22   
11998  Let $d$ be the degree of $P(x).$  Then the deg...        x^2 + x   
11999  We have $\sin\theta = \cos(90^\circ - \theta),...       35^\circ   

                      subject  level                               unique_id  
0                     Algebra      3                     test/algebra/1.json  
1                  Prealgebra      2               test/prealgebra/2002.json  
2      Counting & Probability      5  test/counting_and_probability/967.json  
3                  Prealgebra      4               test/prealgebra/2017.json  
4      Counting & Probability      5  test/counting_and_probability/990.json  
...                       ...    ...                                     ...  
11995                 Algebra      4                  train/algebra/815.json  
11996           Number Theory      4            train/number_theory/144.json  
11997                 Algebra      2                 train/algebra/1959.json  
11998    Intermediate Algebra      5     train/intermediate_algebra/188.json  
11999             Precalculus      4              train/precalculus/639.json  

[12000 rows x 6 columns]

In [22]:
# train_ph problem_nly column and train_split problem column, find what column names are different
train_ph_problems = set(train_ph['problem_nly'].unique())
train_split_problems = set(train_split['problem'].unique())

len(train_split_problems - train_ph_problems ), len(train_ph_problems - train_split_problems)

(1174, 10)

In [23]:

display(pd.read_json(path_or_buf=prm_split_path["test"], lines=True))

display(pd.read_json(path_or_buf=prm_split_path["train"], lines=True))



problem  \
0    Convert the point $(0,3)$ in rectangular coord...   
1    Define\n\[p = \sum_{k = 1}^\infty \frac{1}{k^2...   
2    If $f(x) = \frac{3x-2}{x-2}$, what is the valu...   
3    How many positive whole-number divisors does 1...   
4    The results of a cross-country team's training...   
..                                                 ...   
495  What is the domain of the function $f(x) = \fr...   
496  Let $z = 1+i$ and $w = \dfrac{3z+1}{5z+7}$. Fi...   
497  An equiangular octagon has four sides of lengt...   
498  A sequence $(a_n)$ is defined as follows:\n\[a...   
499  Altitudes $\overline{AD}$ and $\overline{BE}$ ...   

                                              solution  \
0    We have that $r = \sqrt{0^2 + 3^2} = 3.$  Also...   
1    We count the number of times $\frac{1}{n^3}$ a...   
2    $f(-2)+f(-1)+f(0)=\frac{3(-2)-2}{-2-2}+\frac{3...   
3    First prime factorize $196=2^2\cdot7^2$.  The ...   
4    Evelyn covered more distance in less time than...   
..                                                 ...   
495  The inner logarithm is only defined if $x - 2 ...   
496  Plugging in, we have $w = \dfrac{3(1+i)+1}{5(1...   
497  The octagon can be partitioned into five squar...   
498  First, if $a_3 = a_1,$ then\n\[a_1 = a_3 = a_5...   
499  First, we build a diagram:\n\n[asy]\n\nsize(15...   

                              answer               subject  level  \
0    \left( 3, \frac{\pi}{2} \right)           Precalculus      2   
1                              p - q  Intermediate Algebra      5   
2                       \frac{14}{3}               Algebra      3   
3                                  9         Number Theory      3   
4                      \text{Evelyn}               Algebra      2   
..                               ...                   ...    ...   
495             (2,12) \cup (12,102)  Intermediate Algebra      4   
496                     \frac{5}{13}  Intermediate Algebra      3   
497                      \frac{7}{2}              Geometry      5   
498                               -1  Intermediate Algebra      5   
499                        106^\circ              Geometry      4   

                               unique_id  
0              test/precalculus/807.json  
1    test/intermediate_algebra/1994.json  
2                 test/algebra/2584.json  
3            test/number_theory/572.json  
4                 test/algebra/1349.json  
..                                   ...  
495  test/intermediate_algebra/1981.json  
496  test/intermediate_algebra/1232.json  
497               test/geometry/561.json  
498  test/intermediate_algebra/1508.json  
499               test/geometry/615.json  

[500 rows x 6 columns]

problem  \
0      How many vertical asymptotes does the graph of...   
1       If $5x - 3 = 12$, what is the value of $5x + 3$?   
2      Ryan has 3 red lava lamps and 3 blue lava lamp...   
3      Alice wants to buy $3$ pounds of veal at the g...   
4      On the $xy$-plane, the origin is labeled with ...   
...                                                  ...   
11995  The product of two positive integers plus thei...   
11996  The volume of the box is 240 cubic units where...   
11997  Let \[f(n) =\n\begin{cases}\nn^2-1 & \text{ if...   
11998  Find the nonconstant polynomial $P(x)$ such th...   
11999  If $\sqrt2 \sin 10^\circ$ can be written as $\...   

                                                solution         answer  \
0      The denominator of the rational function facto...              2   
1      Adding 6 to both sides of $5x - 3 =12$ gives $...             18   
2      There are $\binom{6}{3}=20$ ways for Ryan to a...  \dfrac{7}{20}   
3      Since Alice wants to buy $3$ pounds of veal, w...           1.36   
4      From the M, we can proceed to four different A...             28   
...                                                  ...            ...   
11995  Let our numbers be $a$ and $b$ with $a>b.$ The...             19   
11996  The prime factorization of 240 is $2^4\cdot3\c...             10   
11997  Working from the inside out, since $2<4$ we ha...             22   
11998  Let $d$ be the degree of $P(x).$  Then the deg...        x^2 + x   
11999  We have $\sin\theta = \cos(90^\circ - \theta),...       35^\circ   

                      subject  level                               unique_id  
0                     Algebra      3                     test/algebra/1.json  
1                  Prealgebra      2               test/prealgebra/2002.json  
2      Counting & Probability      5  test/counting_and_probability/967.json  
3                  Prealgebra      4               test/prealgebra/2017.json  
4      Counting & Probability      5  test/counting_and_probability/990.json  
...                       ...    ...                                     ...  
11995                 Algebra      4                  train/algebra/815.json  
11996           Number Theory      4            train/number_theory/144.json  
11997                 Algebra      2                 train/algebra/1959.json  
11998    Intermediate Algebra      5     train/intermediate_algebra/188.json  
11999             Precalculus      4              train/precalculus/639.json  

[12000 rows x 6 columns]

In [24]:
json.loads(open(dreamprm_meta, 'r').read())[:3]

[{'id': 2,
  'true_false': True,
  'input': "Question: The following diagram shows the bacteriorhodopsin protein.This protein have quaternary structure.\nOptions: (A) True (B) False\n\nStep 1: Restate the question.\n   - The question is asking whether the bacteriorhodopsin protein has a quaternary structure based on the provided diagram.\n\nStep 2: Gather evidence from the image.\n   - The image shows a representation of the bacteriorhodopsin protein. However, the specific details of the protein's structure, such as its quaternary structure, are not visible in the image.\n\nStep 3: Identify any background knowledge needed.\n   - Bacteriorhodopsin is a protein found in the cell membrane of certain archaea.\n   - It functions as a light-driven proton pump.\n   - The protein structure of bacteriorhodopsin includes primary, secondary, and tertiary structures, but quaternary structure refers to the arrangement of multiple protein subunits.\n\nStep 4: Reason with the current evidence.\n   - 

In [5]:
dreamprm_ds = json.loads(open(dreamprm_train, 'r').read())

In [8]:
print(dreamprm_ds[0]['input'])

Your task is to answer the question below. Give step by step reasoning before you answer, and when you're ready to answer, please use the format "Final answer: .."

Question:

What is O in the diagram?
nucleus
membrane
cell wall
cell membrane
Please answer the question based on the options mentioned before.


In [18]:
for i in dreamprm_ds:
    if i['id'] == 70:
        print(i['add'])
        print(i['accuracy'], i['score'], i['ground_truth'])


# print(dreamprm_ds[0]['add'])

Let's analyze the question step by step.

Step 1: Restate the question.
   - The question asks what category the hawk belongs to in the food web: Primary Consumer, Tertiary Consumer, Producer, or Secondary Consumer.

Step 2: Gather evidence from the image.
   - The food web shows various organisms and their feeding relationships.
   - The hawk is shown at the top of the food web, with arrows pointing to it from honeyeaters and emu wrens.

Step 3: Identify any background knowledge needed.
   - In a food web, producers are typically plants or other autotrophs that produce their own food through photosynthesis.
   - Primary consumers are herbivores that eat producers.
   - Secondary consumers are carnivores that eat primary consumers.
   - Tertiary consumers are carnivores that eat secondary consumers.


0.6666666666666666 8 Secondary Consumer
Let's analyze the question step by step.

Step 1: Restate the question.
   - The question asks what category the hawk belongs to in the food web: P

In [3]:
json.loads(open(dreamprm_train, 'r').read())[:3]

[{'id': 787,
  'sid': 4,
  'input': 'Your task is to answer the question below. Give step by step reasoning before you answer, and when you\'re ready to answer, please use the format "Final answer: .."\n\nQuestion:\n\nWhat is O in the diagram?\nnucleus\nmembrane\ncell wall\ncell membrane\nPlease answer the question based on the options mentioned before.',
  'add': 'Step 1: Restate the question.\n   - The question is asking to identify what "O" represents in the diagram.\n\nStep 2: Gather evidence from the image.\n   - The image shows a plant cell with various labeled parts.\n   - "O" is labeled on the outermost layer of the cell.\n\nStep 3: Identify any background knowledge needed.\n   - In plant cells, the outermost layer is the cell wall.\n   - The cell wall provides structural support and protection.\n\nStep 4: Reason with the current evidence.\n   - The diagram shows "O" on the outermost layer of the cell.\n   - Based on the options provided, the cell wall is the correct label for 

In [26]:
MATH['train'].keys()

dict_keys(['prealgebra', 'algebra', 'number_theory', 'precalculus', 'intermediate_algebra', 'counting_and_probability', 'geometry'])

In [27]:
def len_per_key(data):
    return {k: len(v) for k, v in data.items()}

print(len_per_key(MATH['train']))
print(len_per_key(MATH['test']))


# In order to avoid the risk of over-fitting on the 7,500 MATH training problems, we expanded the training set to include 4,500 MATH test split 
# problems. We therefore evaluate our models only on the remaining 500 held-out problems. We selected these 500 test problems uniformly at random, 
# and we believe they are representative of the test set as a whole.

{'prealgebra': 1205, 'algebra': 1744, 'number_theory': 869, 'precalculus': 746, 'intermediate_algebra': 1295, 'counting_and_probability': 771, 'geometry': 870}
{'prealgebra': 871, 'algebra': 1187, 'number_theory': 540, 'precalculus': 546, 'intermediate_algebra': 903, 'counting_and_probability': 474, 'geometry': 479}


In [28]:
json.loads(open(MATH['train']['prealgebra'][0], 'r').read())

{'problem': 'How many positive divisors does $24$ have?',
 'level': 'Level 2',
 'type': 'Prealgebra',
 'solution': 'We will find the positive divisors of 24 by finding pairs that multiply to 24.  We begin with $1$ and $24$, so our list is $$1 \\quad \\underline{\\hphantom{10}} \\quad \\dots \\quad \\underline{\\hphantom{10}} \\quad 24.$$  Checking $2$, we find that $2\\cdot 12=24$, so our list becomes $$1 \\quad 2 \\quad \\underline{\\hphantom{10}} \\quad \\dots \\quad \\underline{\\hphantom{10}} \\quad 12 \\quad 24.$$  Checking $3$, we find that $3\\cdot 8=24$, so our list becomes $$1 \\quad 2 \\quad 3 \\quad \\underline{\\hphantom{10}} \\quad \\dots \\quad \\underline{\\hphantom{10}} \\quad 8 \\quad 12 \\quad 24.$$  Checking $4$, we find that $4\\cdot 6=24$, so our list becomes $$1 \\quad 2 \\quad 3 \\quad 4 \\quad \\underline{\\hphantom{10}} \\quad \\dots \\quad \\underline{\\hphantom{10}} \\quad 6 \\quad 8 \\quad 12 \\quad 24.$$  Checking $5$, we find that $24$ is not divisible by 

In [ ]:
for row in train_ph.iterrows():
    print(row)
    break

(0, labeler                                       e90a38f3-3135-4465-87af-3e6322e3d772
timestamp                                               2022-07-13 18:55:54.496450
generation                                                                     NaN
is_quality_control_question                                                  False
is_initial_screening_question                                                False
question                         {'problem': 'How many seconds are in 7.8 minut...
label                            {'steps': [{'completions': [{'text': '7.8 minu...
question_str                     {'problem': 'How many seconds are in 7.8 minut...
problem_nly                                   How many seconds are in 7.8 minutes?
label_str                        {'steps': [{'completions': [{'text': '7.8 minu...
Name: 0, dtype: object)


In [48]:
from datasets import load_dataset, Dataset, concatenate_datasets, DatasetDict
import pandas as pd
from tqdm import tqdm


splits = ["train", "test"]


def augment(row):
    new_completions = []
    new_labels = []
    for t, l in zip(row["trajectories"], row["trajectories_labels"]):
        new_completions.append(row["completions"] + [t])
        new_labels.append(row["labels"] + [l])
    row["new_completions"] = new_completions
    row["new_labels"] = new_labels
    return row



def unnest_dataset_lists(
    dataset: Dataset,
    list_columns: str | list[str],
) -> Dataset:
    """
    Unnest list columns in a datasets.Dataset where each row contains a list of lists.
    Each inner list becomes a new row, maintaining alignment across specified columns.
    
    Args:
        dataset: The input datasets.Dataset
        list_columns: Column name(s) containing lists to unnest
        
    Returns:
        A new datasets.Dataset with unnested rows
    """
    df = dataset.to_pandas()
    
    if isinstance(list_columns, str):
        list_columns = [list_columns]
    
    # Create rows for each completion/label pair
    rows = []
    
    for idx, row in df.iterrows():
        # Get number of completions for this row
        num_completions = len(row[list_columns[0]])
        
        # For each completion
        for completion_idx in range(num_completions):
            new_row = {}
            
            # Copy non-list columns
            for col in df.columns:
                if col not in list_columns:
                    new_row[col] = row[col]
            
            # Add index to keep the reference to the prompt
            new_row['index'] = idx
            
            # Add list columns
            for col in list_columns:
                new_row[col] = row[col][completion_idx]
            
            rows.append(new_row)
    
    # Create new dataframe
    result_df = pd.DataFrame(rows)
    
    # Convert back to datasets.Dataset
    return Dataset.from_pandas(result_df)

full_ds = DatasetDict()

for split in splits:
    print("Split:", split)
    datasets = []
    for i, ds in enumerate(prm800k):
        ds = prm800k[ds]
        ds = pd.read_json(path_or_buf=ds[split], lines=True)
        print("phase:", i + 1)
        new_ds = []
        for row in tqdm(ds.iterrows(), total=len(ds)):
            row = row[1]  # Get the row data
            solution = []
            trajectories = []
            trajectories_labels = []
            label = []
            new_row = {}
            new_row["prompt"] = row["question"]["problem"]

            for step in row["label"]["steps"]:
                completions = step["completions"]
                if not completions:
                    continue
                if step["chosen_completion"] is None:
                    # Haven't found any relevant point here, discard them for the moment
                    #continue
                    if len(completions) > 1:
                        trajectories = []
                        trajectories_labels = []
                        for c in completions:
                            trajectories.append(c["text"])
                            trajectories_labels.append(not (c["rating"] == -1))
                        # We can continue here assuming there shouldn't be any more trajectories after this point
                        continue

                else:
                    completion = completions[step["chosen_completion"]]
                    solution.append(completion["text"])
                    label.append(not (completion["rating"] == -1))
                    continue

            new_row["trajectories"] = trajectories
            new_row["trajectories_labels"] = trajectories_labels
            new_row["completions"] = solution
            new_row["labels"] = label
            new_ds.append(new_row)

        new_ds = Dataset.from_list(new_ds)

        # Augment the dataset by adding the trajectories as completions
        ds_updated = new_ds.map(augment, num_proc=8)

        # Similar to a pd.DataFrame.explode, get a row per each nested list in the dataset,
        # so that we have all the possible alternative completions in separate rows
        print("Start unnesting...")
        updated = unnest_dataset_lists(
            ds_updated.select_columns(
                ["prompt", "new_completions", "new_labels"]
            ),
            ["new_completions", "new_labels"]
        ).rename_columns(
            {"new_completions": "completions", "new_labels": "labels"}
        ).select_columns(["prompt", "completions", "labels", "index"])  # Sort the column names

        datasets.append(updated)
    
    full_ds[split] = concatenate_datasets(datasets)

Split: train
phase: 1


100%|██████████| 949/949 [00:00<00:00, 15448.42it/s]


Map (num_proc=8):   0%|          | 0/949 [00:00<?, ? examples/s]

Start unnesting...
phase: 2


100%|██████████| 97782/97782 [00:05<00:00, 16456.94it/s]


Map (num_proc=8):   0%|          | 0/97782 [00:00<?, ? examples/s]

Start unnesting...
Split: test
phase: 1


100%|██████████| 106/106 [00:22<00:00,  4.81it/s]


Map (num_proc=8):   0%|          | 0/106 [00:00<?, ? examples/s]

Start unnesting...
phase: 2


100%|██████████| 2762/2762 [00:00<00:00, 22469.63it/s]


Map (num_proc=8):   0%|          | 0/2762 [00:00<?, ? examples/s]

Start unnesting...


In [ ]:
a = ds_updated.to_pandas()
a.iloc[0]['completions']

In [ ]:
unset_a = unnest_dataset_lists(
            Dataset.from_pandas(a[:1]).select_columns(
                ["prompt", "new_completions", "new_labels"]
            ),
            ["new_completions", "new_labels"]
        ).rename_columns(
            {"new_completions": "completions", "new_labels": "labels"}
        ).select_columns(["prompt", "completions", "labels", "index"]).to_pandas()['completions']  # Sort the column names

for i in zip(*tuple(unset_a)):
    print(len(set(i)), set(i))

In [54]:
df = full_ds['train'].to_pandas()

In [57]:
df

prompt  \
0       How many positive two-digit integers leave a r...   
1       How many positive two-digit integers leave a r...   
2       How many positive two-digit integers leave a r...   
3       How many positive two-digit integers leave a r...   
4       How many positive two-digit integers leave a r...   
...                                                   ...   
389720  Suppose we are given seven points that are equ...   
389721  Suppose we are given seven points that are equ...   
389722  Suppose we are given seven points that are equ...   
389723  Suppose we are given seven points that are equ...   
389724  Suppose we are given seven points that are equ...   

                                              completions  \
0       [So if a number leaves a remainder of 2 when d...   
1       [So if a number leaves a remainder of 2 when d...   
2       [So if a number leaves a remainder of 2 when d...   
3       [So if a number leaves a remainder of 2 when d...   
4       [So if a number leaves a remainder of 2 when d...   
...                                                   ...   
389720  [I notice that the problem is asking about the...   
389721  [I notice that the problem is asking about the...   
389722  [I notice that the problem is asking about the...   
389723  [I notice that the problem is asking about the...   
389724  [I notice that the problem is asking about the...   

                                                   labels  index  \
0       [True, True, True, True, True, True, True, Tru...      1   
1       [True, True, True, True, True, True, True, Tru...      1   
2       [True, True, True, True, True, True, True, Tru...      1   
3       [True, True, True, True, True, True, True, Tru...      1   
4       [True, True, True, True, True, True, True, Tru...      1   
...                                                   ...    ...   
389720                          [True, True, True, False]  97781   
389721                          [True, True, True, False]  97781   
389722                           [True, True, True, True]  97781   
389723                           [True, True, True, True]  97781   
389724                          [True, True, True, False]  97781   

                                          completions_str  
0       ["So if a number leaves a remainder of 2 when ...  
1       ["So if a number leaves a remainder of 2 when ...  
2       ["So if a number leaves a remainder of 2 when ...  
3       ["So if a number leaves a remainder of 2 when ...  
4       ["So if a number leaves a remainder of 2 when ...  
...                                                   ...  
389720  ['I notice that the problem is asking about th...  
389721  ['I notice that the problem is asking about th...  
389722  ['I notice that the problem is asking about th...  
389723  ['I notice that the problem is asking about th...  
389724  ['I notice that the problem is asking about th...  

[389725 rows x 5 columns]

In [61]:
df['completions_str'] = df['completions'].apply(lambda x: str(x))
df['labels_str'] = df['labels'].apply(lambda x: str(x))
df['prompt_str'] = df['prompt'].astype(str)
df['unique_id'] = df['completions_str'] + df['prompt_str'] + df['labels_str']
print(f"Total unique completions in train set: {len(df['unique_id'].unique())} out of {len(df)} total completions.")

## only keep unique rows
df_unique = df.drop_duplicates(subset=['unique_id'])
df_unique

Total unique completions in train set: 331719 out of 389725 total completions.


prompt  \
0       How many positive two-digit integers leave a r...   
1       How many positive two-digit integers leave a r...   
4       How many positive two-digit integers leave a r...   
5       How many positive two-digit integers leave a r...   
6       How many positive two-digit integers leave a r...   
...                                                   ...   
389720  Suppose we are given seven points that are equ...   
389721  Suppose we are given seven points that are equ...   
389722  Suppose we are given seven points that are equ...   
389723  Suppose we are given seven points that are equ...   
389724  Suppose we are given seven points that are equ...   

                                              completions  \
0       [So if a number leaves a remainder of 2 when d...   
1       [So if a number leaves a remainder of 2 when d...   
4       [So if a number leaves a remainder of 2 when d...   
5       [So if a number leaves a remainder of 2 when d...   
6       [So if a number leaves a remainder of 2 when d...   
...                                                   ...   
389720  [I notice that the problem is asking about the...   
389721  [I notice that the problem is asking about the...   
389722  [I notice that the problem is asking about the...   
389723  [I notice that the problem is asking about the...   
389724  [I notice that the problem is asking about the...   

                                                   labels  index  \
0       [True, True, True, True, True, True, True, Tru...      1   
1       [True, True, True, True, True, True, True, Tru...      1   
4       [True, True, True, True, True, True, True, Tru...      1   
5       [True, True, True, True, True, True, True, Tru...      1   
6       [True, True, True, True, True, True, True, Tru...      1   
...                                                   ...    ...   
389720                          [True, True, True, False]  97781   
389721                          [True, True, True, False]  97781   
389722                           [True, True, True, True]  97781   
389723                           [True, True, True, True]  97781   
389724                          [True, True, True, False]  97781   

                                          completions_str  \
0       ["So if a number leaves a remainder of 2 when ...   
1       ["So if a number leaves a remainder of 2 when ...   
4       ["So if a number leaves a remainder of 2 when ...   
5       ["So if a number leaves a remainder of 2 when ...   
6       ["So if a number leaves a remainder of 2 when ...   
...                                                   ...   
389720  ['I notice that the problem is asking about th...   
389721  ['I notice that the problem is asking about th...   
389722  ['I notice that the problem is asking about th...   
389723  ['I notice that the problem is asking about th...   
389724  ['I notice that the problem is asking about th...   

                                               labels_str  \
0       [ True  True  True  True  True  True  True  Tr...   
1       [ True  True  True  True  True  True  True  Tr...   
4       [ True  True  True  True  True  True  True  Tr...   
5       [ True  True  True  True  True  True  True  Tr...   
6       [ True  True  True  True  True  True  True  Tr...   
...                                                   ...   
389720                          [ True  True  True False]   
389721                          [ True  True  True False]   
389722                          [ True  True  True  True]   
389723                          [ True  True  True  True]   
389724                          [ True  True  True False]   

                                               prompt_str  \
0       How many positive two-digit integers leave a r...   
1       How many positive two-digit integers leave a r...   
4       How many positive two-digit integers leave a r...   
5       How many positive two-digit integers leave a r... 

In [ ]:
# ## df sort by completion str length
# df_unique['completion_length'] = df_unique['completions_str'].apply(len)
# df_unique = df_unique.sort_values(by='completion_length', ascending=True)
# df_unique

prompt  \
136164  Medians $\overline{DP}$ and $\overline{EQ}$ of...   
145431  Find the units digit of the following:  \begin...   
147793  Solve  \[\frac{2x^2+x+3}{x^2+x+1}=\frac{2x+1}{...   
148078  Let $x$ and $y$ be complex numbers such that\n...   
144249  Given that both $i - 3$ and $b$ are roots of $...   
...                                                   ...   
151     Regular octagon $A_1A_2A_3A_4A_5A_6A_7A_8$ is ...   
150     Regular octagon $A_1A_2A_3A_4A_5A_6A_7A_8$ is ...   
148     Regular octagon $A_1A_2A_3A_4A_5A_6A_7A_8$ is ...   
152     Regular octagon $A_1A_2A_3A_4A_5A_6A_7A_8$ is ...   
147     Regular octagon $A_1A_2A_3A_4A_5A_6A_7A_8$ is ...   

                                              completions  \
136164                                                [0]   
145431                                                [6]   
147793                                                [1]   
148078                                                [2]   
144249                                                [2]   
...                                                   ...   
151     [This would be the area of the sector of the c...   
150     [This would be the area of the sector of the c...   
148     [This would be the area of the sector of the c...   
152     [This would be the area of the sector of the c...   
147     [This would be the area of the sector of the c...   

                                                   labels  index  \
136164                                            [False]  37013   
145431                                            [False]  39121   
147793                                            [False]  39679   
148078                                            [False]  39745   
144249                                            [False]  38845   
...                                                   ...    ...   
151     [True, True, True, True, True, True, True, Tru...     34   
150     [True, True, True, True, True, True, True, Tru...     34   
148     [True, True, True, True, True, True, True, Tru...     34   
152     [True, True, True, True, True, True, True, Tru...     34   
147     [True, True, True, True, True, True, True, Tru...     34   

                                          completions_str  \
136164                                              ['0']   
145431                                              ['6']   
147793                                              ['1']   
148078                                              ['2']   
144249                                              ['2']   
...                                                   ...   
151     ['This would be the area of the sector of the ...   
150     ['This would be the area of the sector of the ...   
148     ['This would be the area of the sector of the ...   
152     ['This would be the area of the sector of the ...   
147     ['This would be the area of the sector of the ...   

                                               labels_str  \
136164                                            [False]   
145431                                            [False]   
147793                                            [False]   
148078                                            [False]   
144249                                            [False]   
...                                                   ...   
151     [ True  True  True  True  True  True  True  Tr...   
150     [ True  True  True  True  True  True  True  Tr...   
148     [ True  True  True  True  True  True  True  Tr...   
152     [ True  True  True  True  True  True  True  Tr...   
147     [ True  True  True  True  True  True  True  Tr...   

                                               prompt_str  \
136164  Medians $\overline{DP}$ and $\overline{EQ}$ of...   
145431  Find the units digit of the following:  \begin...   
147793  Solve  \[\frac{2x^2+x+3}{x^2+x+1}=\frac{2x+1}{...   
148078  Let $x$ and $y$ be complex numbers such that\n... 

In [79]:
## drop columns that are not needed
df_unique = df_unique.drop(columns=['completions_str', 'labels_str', 'prompt_str', 'unique_id', 'completion_length'])
df_unique

prompt  \
136164  Medians $\overline{DP}$ and $\overline{EQ}$ of...   
145431  Find the units digit of the following:  \begin...   
147793  Solve  \[\frac{2x^2+x+3}{x^2+x+1}=\frac{2x+1}{...   
148078  Let $x$ and $y$ be complex numbers such that\n...   
144249  Given that both $i - 3$ and $b$ are roots of $...   
...                                                   ...   
151     Regular octagon $A_1A_2A_3A_4A_5A_6A_7A_8$ is ...   
150     Regular octagon $A_1A_2A_3A_4A_5A_6A_7A_8$ is ...   
148     Regular octagon $A_1A_2A_3A_4A_5A_6A_7A_8$ is ...   
152     Regular octagon $A_1A_2A_3A_4A_5A_6A_7A_8$ is ...   
147     Regular octagon $A_1A_2A_3A_4A_5A_6A_7A_8$ is ...   

                                              completions  \
136164                                                [0]   
145431                                                [6]   
147793                                                [1]   
148078                                                [2]   
144249                                                [2]   
...                                                   ...   
151     [This would be the area of the sector of the c...   
150     [This would be the area of the sector of the c...   
148     [This would be the area of the sector of the c...   
152     [This would be the area of the sector of the c...   
147     [This would be the area of the sector of the c...   

                                                   labels  index  
136164                                            [False]  37013  
145431                                            [False]  39121  
147793                                            [False]  39679  
148078                                            [False]  39745  
144249                                            [False]  38845  
...                                                   ...    ...  
151     [True, True, True, True, True, True, True, Tru...     34  
150     [True, True, True, True, True, True, True, Tru...     34  
148     [True, True, True, True, True, True, True, Tru...     34  
152     [True, True, True, True, True, True, True, Tru...     34  
147     [True, True, True, True, True, True, True, Tru...     34  

[331719 rows x 4 columns]

In [ ]:
train_split
### inner join on problem and prompt between df_unique and train_split
df_unique = df_unique.merge(train_split, left_on='prompt', right_on='problem', how='inner')
df_unique = df_unique.drop(columns=['unique_id', 'solution', 'problem'])
df_unique

prompt  \
0       Medians $\overline{DP}$ and $\overline{EQ}$ of...   
1       Medians $\overline{DP}$ and $\overline{EQ}$ of...   
2       Medians $\overline{DP}$ and $\overline{EQ}$ of...   
3       Medians $\overline{DP}$ and $\overline{EQ}$ of...   
4       Medians $\overline{DP}$ and $\overline{EQ}$ of...   
...                                                   ...   
327792                    Factor $x^3 - 9x^2 + 27x - 35$.   
327793                    Factor $x^3 - 9x^2 + 27x - 35$.   
327794                    Factor $x^3 - 9x^2 + 27x - 35$.   
327795                    Factor $x^3 - 9x^2 + 27x - 35$.   
327796                    Factor $x^3 - 9x^2 + 27x - 35$.   

                                              completions  \
0                                                     [0]   
1       [I'm going to draw a diagram to visualize the ...   
2       [I want to find the length of DF, which is a s...   
3       [I notice that the two medians form a right tr...   
4       [I need to find the length of DF, which is one...   
...                                                   ...   
327792  [This is a cubic polynomial, so I'm looking fo...   
327793  [This is a cubic polynomial, so I'm looking fo...   
327794  [This is a cubic polynomial, so I'm looking fo...   
327795  [This is a cubic polynomial, so I'm looking fo...   
327796  [This is a cubic polynomial, so I'm looking fo...   

                                                   labels  index  \
0                                                 [False]  37013   
1                                                  [True]  34004   
2                                                  [True]  49405   
3                                                  [True]  34004   
4                                                  [True]  49405   
...                                                   ...    ...   
327792  [True, True, True, True, True, True, True, Tru...  66783   
327793  [True, True, True, True, True, True, True, Tru...  66783   
327794  [True, True, True, True, True, True, True, Tru...  66783   
327795  [True, True, True, True, True, True, True, Tru...  66783   
327796  [True, True, True, True, True, True, True, Tru...  66783   

                                                  problem  \
0       Medians $\overline{DP}$ and $\overline{EQ}$ of...   
1       Medians $\overline{DP}$ and $\overline{EQ}$ of...   
2       Medians $\overline{DP}$ and $\overline{EQ}$ of...   
3       Medians $\overline{DP}$ and $\overline{EQ}$ of...   
4       Medians $\overline{DP}$ and $\overline{EQ}$ of...   
...                                                   ...   
327792                    Factor $x^3 - 9x^2 + 27x - 35$.   
327793                    Factor $x^3 - 9x^2 + 27x - 35$.   
327794                    Factor $x^3 - 9x^2 + 27x - 35$.   
327795                    Factor $x^3 - 9x^2 + 27x - 35$.   
327796                    Factor $x^3 - 9x^2 + 27x - 35$.   

                                                 solution           answer  \
0       [asy]\npair D,EE,F,P,Q,G;\n\nG = (0,0);\nD = (...       8\sqrt{13}   
1       [asy]\npair D,EE,F,P,Q,G;\n\nG = (0,0);\nD = (...       8\sqrt{13}   
2       [asy]\npair D,EE,F,P,Q,G;\n\nG = (0,0);\nD = (...       8\sqrt{13}   
3       [asy]\npair D,EE,F,P,Q,G;\n\nG = (0,0);\nD = (...       8\sqrt{13}   
4       [asy]\npair D,EE,F,P,Q,G;\n\nG = (0,0);\nD = (...       8\sqrt{13}   
...                                                   ...              ...   
327792  We could check to see which divisors of $-35$ ...  (x-5)(x^2-4x+7)   
327793  We could check to see which divisors of $-35$ ...  (x-5)(x^2-4x+7)   
327794  We could check to see which divisors of $-35$ ...  (x-5)(x^2-4x+7)   
327795  We could check to see which divisors of $-35$ ...  (x-5)(x^2-4x+7)   
327796  We could check to see which divisors of $-35$ ...  (x-5)(x^2-4x+7)   

                     subject  level                            unique_id  
0                   Geo

In [ ]:
### convert it to hugginface dataset
from datasets import Dataset
hf_dataset = Dataset.from_pandas(df_unique)

In [33]:
qns = set(full_ds['train']['prompt'])
# train_ph problem_nly column and train_split problem column, find what column names are different
train_ph_problems = set(train_ph['problem_nly'].unique())
train_split_problems = set(train_split['problem'].unique())

len(train_split_problems - train_ph_problems ), len(train_ph_problems - train_split_problems)

(1174, 10)

In [35]:
len(train_ph_problems - qns), len(train_split_problems - qns)

(1048, 2221)

In [34]:
len(qns - train_ph_problems), len(qns - train_split_problems)

(0, 9)

In [4]:
from transformers import AutoTokenizer
class ARGS:
    train_batch_size = 20
    meta_batch_size = 1
    model_type = "clf"
    add_new_token = True
    meta_dataset = "AIME"
    filter_dataset_steps = 20
    filter_dataset_token_size = 2700
    overfit = False
    reward_model = "Qwen/Qwen2.5-Math-7B-Instruct"
    
args = ARGS()
tokenizer = AutoTokenizer.from_pretrained(args.reward_model, trust_remote_code=True)
if args.add_new_token:
    new_tokens = ['<PRM_STEP_SCORE>']
    num_added_tokens = tokenizer.add_tokens(new_tokens)


In [6]:

import importlib
sanity_check = False

import prm_data
importlib.reload(prm_data)
from prm_data import build_dataloader


(
    train_dataloader,
    meta_dataloader,
    dataloader_benchmark,
    validation_dataloader
) = build_dataloader(
    tokenizer=tokenizer,
    train_batch_size= args.train_batch_size,
    meta_batch_size= args.meta_batch_size,
    inf_batch_size=1,
    token_based=True,
    add_new_token=args.add_new_token,
    meta_dataset=args.meta_dataset,
    sanity_check=sanity_check,
    filter_dataset_steps=args.filter_dataset_steps,
    filter_dataset_token_size=args.filter_dataset_token_size,
    overfit = args.overfit,
)


Dataset loaded with 326767 samples.
Filtering dataset to steps <= 20
dataset size after step filter: 322213
Loading preprocessed dataset from pre_322213_qwen_math_dataset.pkl
Filtering dataset to token size <= 2700
Filtered dataset size: 322213


100%|██████████| 322213/322213 [00:22<00:00, 14430.74it/s]


Loading preprocessed dataset from 1853280_qwen_math_dataset.pkl
Sanity check mode: max steps idx = [20, 368], max len idx = [20, 1205]
Total number of samples: 1853280, 322213


tensor([1, 1]) tensor([ True, False])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1]) tensor([ True,  True,  True,  True,  True,  True,  True,  True, False])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]) tensor([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False])
tensor([1]) tensor([True])
tensor([1, 1, 1, 1, 1, 1, 1]) tensor([ True,  True,  True,  True,  True,  True, False])
tensor([1, 1, 1, 1]) tensor([True, True, True, True])
tensor([1, 1, 1, 1, 1]) tensor([True, True, True, True, True])
tensor([1]) tensor([False])
tensor([1, 1, 1, 1]) tensor([True, True, True, True])
tensor([1, 1]) tensor([True, True])
tensor([1, 1, 1, 1, 1, 1]) tensor([ True,  True,  True,  True,  True, False])
tensor([1, 1, 1, 1, 1]) tensor([True, True, True, True, True])
tensor([1, 1, 1, 1, 1, 1, 1, 1]) tensor

100%|██████████| 9273/9273 [00:02<00:00, 3584.75it/s]


Sanity check mode: max steps idx = [20, 812], max len idx = [13, 2700]
Total number of samples: 9273, 733


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]) tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True])
Loading aime_outputs/test2025-II/o4-mini/AIME_o4_mini_8_traj_25_II.jsonl with 15 samples
Dataset loaded with 120 samples.
dataset size after step filter: 120


100%|██████████| 120/120 [00:00<00:00, 6127.77it/s]


Loading preprocessed dataset from 164_qwen_math_dataset.pkl
Sanity check mode: max steps idx = [9, 981], max len idx = [1, 1637]
Total number of samples: 164, 120


tensor([1, 1, 1, 1]) tensor([True, True, True, True])
Loading aime_outputs/test2025-II/o4-mini-8-diverse/AIME_o4_mini_diverse_traj_25_II.jsonl with 15 samples
Dataset loaded with 120 samples.
dataset size after step filter: 120


100%|██████████| 120/120 [00:00<00:00, 6440.88it/s]

Loading preprocessed dataset from 126_qwen_math_dataset.pkl
Sanity check mode: max steps idx = [2, 345], max len idx = [1, 1567]
Total number of samples: 126, 120


tensor([1]) tensor([True])
Loading aime_outputs/test2025-II/gemini/Gemini_AIME_Dataset_2024_25_II.jsonl with 15 samples
Dataset loaded with 240 samples.


dataset size after step filter: 240


100%|██████████| 240/240 [00:00<00:00, 3732.80it/s]


Loading preprocessed dataset from 5171_qwen_math_dataset.pkl
Sanity check mode: max steps idx = [46, 5714], max len idx = [35, 7921]
Total number of samples: 5171, 240


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1]) tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True])
Loading aime_outputs/test2025-I/o4-mini/AIME_o4_mini_8_traj_25_I.jsonl with 15 samples
Dataset loaded with 120 samples.
dataset size after step filter: 120


100%|██████████| 120/120 [00:00<00:00, 5443.02it/s]


Loading preprocessed dataset from 713_qwen_math_dataset.pkl
Sanity check mode: max steps idx = [29, 833], max len idx = [1, 1957]
Total number of samples: 713, 120


tensor([1, 1, 1]) tensor([True, True, True])
Loading aime_outputs/test2025-I/o4-mini-8-diverse/AIME_o4_mini_diverse_traj_25_I.jsonl with 15 samples
Dataset loaded with 120 samples.
dataset size after step filter: 120


100%|██████████| 120/120 [00:00<00:00, 5848.17it/s]

Loading preprocessed dataset from 122_qwen_math_dataset.pkl
Sanity check mode: max steps idx = [2, 377], max len idx = [1, 1580]
Total number of samples: 122, 120


tensor([1]) tensor([True])
Loading aime_outputs/test2025-I/gemini/Gemini_AIME_Dataset_2024_25_I.jsonl with 15 samples


Dataset loaded with 240 samples.
dataset size after step filter: 240


100%|██████████| 240/240 [00:00<00:00, 4544.08it/s]


Loading preprocessed dataset from 5538_qwen_math_dataset.pkl
Sanity check mode: max steps idx = [48, 8627], max len idx = [44, 9377]
Total number of samples: 5538, 240


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]) tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True])
Dataset loaded with 121 samples.
dataset size after step filter: 121


100%|██████████| 2287/2287 [00:00<00:00, 9845.96it/s] 


Sanity check mode: max steps idx = [51, 1363], max len idx = [51, 1363]
Total number of samples: 2287, 121


