In [2]:
train_dataset = load_dataset("FrozenWolf/prm800k")

In [1]:
from datasets import load_dataset
# from trl import PRMConfig, PRMTrainer
from transformers import AutoModelForTokenClassification, AutoTokenizer
model = "Qwen/Qwen2.5-Math-7B-Instruct"
from prm_data import *
tokenizer = AutoTokenizer.from_pretrained(model)
new_tokens = ['<PRM_STEP_SCORE>']
num_added_tokens = tokenizer.add_tokens(new_tokens)

dataloader_benchmark = build_vanilla_inference_dataloader(
    tokenizer=tokenizer,
    meta_batch_size=1
)


Loading aime_outputs/test2025-II/o4-mini/AIME_o4_mini_8_traj_25_II.jsonl with 15 samples
Dataset loaded with 120 samples.
dataset size after step filter: 120


100%|██████████| 120/120 [00:00<00:00, 10642.29it/s]


Loading preprocessed dataset from 164_qwen_math_dataset.pkl
Sanity check mode: max steps idx = [9, 981], max len idx = [1, 1637]
Total number of samples: 164, 120


151665 [True, True, True, True]
tensor([[False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         Fals

100%|██████████| 120/120 [00:00<00:00, 9604.54it/s]


Loading preprocessed dataset from 126_qwen_math_dataset.pkl
Sanity check mode: max steps idx = [2, 345], max len idx = [1, 1567]
Total number of samples: 126, 120


151665 [True]
tensor([[False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, F

100%|██████████| 240/240 [00:00<00:00, 7042.25it/s]


Loading preprocessed dataset from 5171_qwen_math_dataset.pkl
Sanity check mode: max steps idx = [46, 5714], max len idx = [35, 7921]
Total number of samples: 5171, 240


151665 [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
tensor([[False, False, False,  ..., False, False,  True]])
Loading aime_outputs/test2025-I/o4-mini/AIME_o4_mini_8_traj_25_I.jsonl with 15 samples
Dataset loaded with 120 samples.
dataset size after step filter: 120


100%|██████████| 120/120 [00:00<00:00, 10101.89it/s]


Loading preprocessed dataset from 713_qwen_math_dataset.pkl
Sanity check mode: max steps idx = [29, 833], max len idx = [1, 1957]
Total number of samples: 713, 120


151665 [True, True, True]
tensor([[False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False,  True, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False,  T

100%|██████████| 120/120 [00:00<00:00, 10796.15it/s]


Loading preprocessed dataset from 122_qwen_math_dataset.pkl
Sanity check mode: max steps idx = [2, 377], max len idx = [1, 1580]
Total number of samples: 122, 120


151665 [True]
tensor([[False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, F

100%|██████████| 240/240 [00:00<00:00, 7581.49it/s]

Loading preprocessed dataset from 5538_qwen_math_dataset.pkl
Sanity check mode: max steps idx = [48, 8627], max len idx = [44, 9377]
Total number of samples: 5538, 240


151665 [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
tensor([[False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False,  True, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False,

In [1]:
from prm_data import *
# train_prm.py
from datasets import load_dataset
from trl import PRMConfig, PRMTrainer
from transformers import AutoModelForTokenClassification, AutoTokenizer

model = AutoModelForTokenClassification.from_pretrained("Qwen/Qwen2-0.5B", num_labels=2)
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2-0.5B")


(
    train_dataloader,
    meta_dataloader,
    dataloader_benchmark
) = build_dataloader(
    tokenizer=tokenizer,
    train_batch_size= 1,
    meta_batch_size= 1,
    token_based=True,
    add_new_token=False,
    meta_dataset="AIME",
    sanity_check=False,
    filter_dataset_steps=20,
    filter_dataset_token_size=2000
)


/home/frozenwolf/miniconda3/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/frozenwolf/miniconda3/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Some weights of Qwen2ForTokenClassification were not initialized from the model checkpoint at Qwen/Qwen2-0.5B and are newly initialized: ['score.bias', 'score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


['<|im_start|>', '<|im_end|>']
Dataset loaded with 326767 samples.
Filtering dataset to steps <= 20
Separator token is: <|im_end|> {'input_ids': [151645], 'attention_mask': [1]}
dataset size after step filter: 322213
Loading preprocessed dataset from pre_322213_qwen_math_dataset.pkl
Filtering dataset to token size <= 2000
Filtered dataset size: 322213


100%|██████████| 322213/322213 [00:19<00:00, 16417.85it/s]


Loading preprocessed dataset from 1853280_qwen_math_dataset.pkl
Sanity check mode: max steps idx = [20, 368], max len idx = [20, 1205]
Total number of samples: 1853280, 322213


Dataset loaded with 933 samples.
Filtering dataset to steps <= 20
Separator token is: <|im_end|> {'input_ids': [151645], 'attention_mask': [1]}
dataset size after step filter: 826


100%|██████████| 826/826 [00:02<00:00, 317.26it/s]


Filtering dataset to token size <= 2000
Filtered dataset size: 510


100%|██████████| 6429/6429 [00:01<00:00, 5038.45it/s]


Sanity check mode: max steps idx = [20, 812], max len idx = [15, 1998]
Total number of samples: 6429, 510


Loading aime_outputs/test2025-II/o4-mini/AIME_o4_mini_8_traj_25_II.jsonl with 15 samples
Dataset loaded with 120 samples.
Separator token is: <|im_end|> {'input_ids': [151645], 'attention_mask': [1]}
dataset size after step filter: 120


100%|██████████| 164/164 [00:00<00:00, 1364.94it/s]


Sanity check mode: max steps idx = [9, 981], max len idx = [1, 1637]
Total number of samples: 164, 120


Loading aime_outputs/test2025-II/o4-mini-8-diverse/AIME_o4_mini_diverse_traj_25_II.jsonl with 15 samples
Dataset loaded with 120 samples.
Separator token is: <|im_end|> {'input_ids': [151645], 'attention_mask': [1]}
dataset size after step filter: 120


100%|██████████| 126/126 [00:00<00:00, 1208.58it/s]


Sanity check mode: max steps idx = [2, 345], max len idx = [1, 1567]
Total number of samples: 126, 120


Loading aime_outputs/test2025-II/gemini/Gemini_AIME_Dataset_2024_25_II.jsonl with 15 samples
Dataset loaded with 240 samples.
Separator token is: <|im_end|> {'input_ids': [151645], 'attention_mask': [1]}
dataset size after step filter: 240


100%|██████████| 5171/5171 [00:00<00:00, 6672.76it/s]


Sanity check mode: max steps idx = [46, 5714], max len idx = [35, 7921]
Total number of samples: 5171, 240


Loading aime_outputs/test2025-I/o4-mini/AIME_o4_mini_8_traj_25_I.jsonl with 15 samples
Dataset loaded with 120 samples.
Separator token is: <|im_end|> {'input_ids': [151645], 'attention_mask': [1]}
dataset size after step filter: 120


100%|██████████| 713/713 [00:00<00:00, 4424.36it/s]


Sanity check mode: max steps idx = [29, 833], max len idx = [1, 1957]
Total number of samples: 713, 120


Loading aime_outputs/test2025-I/o4-mini-8-diverse/AIME_o4_mini_diverse_traj_25_I.jsonl with 15 samples
Dataset loaded with 120 samples.
Separator token is: <|im_end|> {'input_ids': [151645], 'attention_mask': [1]}
dataset size after step filter: 120


100%|██████████| 122/122 [00:00<00:00, 1287.87it/s]


Sanity check mode: max steps idx = [2, 377], max len idx = [1, 1580]
Total number of samples: 122, 120


Loading aime_outputs/test2025-I/gemini/Gemini_AIME_Dataset_2024_25_I.jsonl with 15 samples
Dataset loaded with 240 samples.
Separator token is: <|im_end|> {'input_ids': [151645], 'attention_mask': [1]}
dataset size after step filter: 240


100%|██████████| 5538/5538 [00:00<00:00, 6545.59it/s]

Sanity check mode: max steps idx = [48, 8627], max len idx = [44, 9377]
Total number of samples: 5538, 240




In [3]:
model.to("cuda")

Qwen2ForTokenClassification(
  (model): Qwen2Model(
    (embed_tokens): Embedding(151936, 896)
    (layers): ModuleList(
      (0-23): 24 x Qwen2DecoderLayer(
        (self_attn): Qwen2Attention(
          (q_proj): Linear(in_features=896, out_features=896, bias=True)
          (k_proj): Linear(in_features=896, out_features=128, bias=True)
          (v_proj): Linear(in_features=896, out_features=128, bias=True)
          (o_proj): Linear(in_features=896, out_features=896, bias=False)
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=896, out_features=4864, bias=False)
          (up_proj): Linear(in_features=896, out_features=4864, bias=False)
          (down_proj): Linear(in_features=4864, out_features=896, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((896,), eps=1e-06)
    (rotary_emb): Qwen

In [18]:
training_args = PRMConfig(
    output_dir="Output-Vannila-Qwen2.5-Math-7B-Instruct",
    eval_steps=10000,    
    logging_dir="./logs",     
    logging_strategy="steps",     
    logging_steps=100,            
    report_to="wandb",         
    save_strategy="epoch",      
    save_total_limit=2,            
    num_train_epochs=5,   per_gpu_train_batch_size=10,  per_gpu_eval_batch_size=1 
)

In [15]:
from eval_aime import eval
device="cuda"
with torch.no_grad():
    for ds_name in dataloader_benchmark:
        for model_name in tqdm(dataloader_benchmark[ds_name]):
            print(f"Evaluating {ds_name} with {model_name}")
            test_dataloader = dataloader_benchmark[ds_name][model_name]
            predictions = None
            for batch in test_dataloader:
                
                score = model(batch['input_ids'].to(device),
                        batch['attention_mask'].to(device)).logits
                # score -> (B, T,)
                outputs = torch.argmax(score[:,-1], dim=-1).cpu()

                outputs = outputs.to(dtype=torch.float32)
                if predictions is None:
                    predictions = outputs.numpy()
                else:
                    predictions = np.concatenate((predictions, outputs.numpy()), axis=0)
            dataset = test_dataloader.dataset.dataset
            predictions, score = eval(dataset, predictions, ds_name)

  0%|          | 0/3 [00:00<?, ?it/s]

Evaluating test2025-II with aime_outputs/test2025-II/o4-mini


 33%|███▎      | 1/3 [00:18<00:36, 18.40s/it]

Pass@1:  14/15 = 0.9333
Consensus (majority voting): 13/15 = 0.8667
Pass@1: 0.25/1 = 0.2500
Evaluating test2025-II with aime_outputs/test2025-II/o4-mini-8-diverse


 67%|██████▋   | 2/3 [00:35<00:17, 17.44s/it]

Pass@1:  13/15 = 0.8667
Consensus (majority voting): 12/15 = 0.8000
Pass@1: 0.5/1 = 0.5000
Evaluating test2025-II with aime_outputs/test2025-II/gemini


100%|██████████| 3/3 [03:16<00:00, 65.52s/it]


Pass@21:  13/15 = 0.8667
Consensus (majority voting): 0/15 = 0.0000
Pass@1: 0.6138930465246258/15 = 0.0409


  0%|          | 0/3 [00:00<?, ?it/s]

Evaluating test2025-I with aime_outputs/test2025-I/o4-mini


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
 33%|███▎      | 1/3 [00:46<01:32, 46.10s/it]

Pass@1:  12/15 = 0.8000
Consensus (majority voting): 1/15 = 0.0667
Pass@1: 1.7773809523809527/11 = 0.1616
Evaluating test2025-I with aime_outputs/test2025-I/o4-mini-8-diverse


 67%|██████▋   | 2/3 [01:18<00:38, 38.24s/it]

Pass@1:  11/15 = 0.7333
Consensus (majority voting): 11/15 = 0.7333
Pass@1: 11/15 = 0.7333
Evaluating test2025-I with aime_outputs/test2025-I/gemini


100%|██████████| 3/3 [05:47<00:00, 115.81s/it]

Pass@27:  13/15 = 0.8667
Consensus (majority voting): 0/15 = 0.0000
Pass@1: 0.7228954925936353/15 = 0.0482


In [14]:
dataset, predictions, ds_name

(Dataset({
     features: ['id', 'problem', 'completions', 'generated_answers', 'gold_answer', 'is_correct', 'answers_correctness', 'majority_voting', 'majority_voting_is_correct', 'prompt', 'index', 'labels', 'subject'],
     num_rows: 120
 }),
 array([0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1.], dtype=float32),
 'test2025-II')

In [6]:
score.logits.shape

torch.Size([1, 847, 2])

In [ ]:

# training_args = PRMConfig(output_dir="Qwen2.5-Math-7B-Instruct")
# trainer = PRMTrainer(model=model, args=training_args, processing_class=tokenizer, train_dataset=train_dataset)
# trainer.train()


# from datasets import load_dataset

# pipe = pipeline("token-classification", model="trl-lib/Qwen2-0.5B-Reward-Math-Sheperd")
# dataset = load_dataset("trl-lib/math_shepherd")
# example = {
#     "prompt": "Musa is the class teacher of a class of 45 students. He wants to split them into three groups by age. If a third of the class is under 11 years, and two-fifths are above 11 but under 13, how many students will be in the third group (13 years and above)?",
#     "completions": [
#         "Step 1: A third of the class is under 11 years because 11 - 1/3 = <<11-1/3=7>>7.",
#         "Step 2: Two-fifths of the class are above 11 but under 13 because 2/5 * 11 = <<2/5*11=8>>8.",
#         "Step 3: There are 45 students, so the third group will have 45 - 7 - 8 = <<45-7-8=20>>20 students. The answer is: 20",
#     ],
#     "labels": [True, False, False],
# }


separator = "\n"  # It's important to use the same separator as the one used during training

for idx in range(1, len(example["completions"]) + 1):
    steps = example["completions"][0:idx]
    text = separator.join((example["prompt"], *steps)) + separator  # Add a separator between the prompt and each steps
    pred_entity = pipe(text)[-1]["entity"]
    pred = {"LABEL_0": False, "LABEL_1": True}[pred_entity]
    label = example["labels"][idx - 1]
    print(f"Step {idx}\tPredicted: {pred} \tLabel: {label}")